In [39]:
from tensorflow.keras.preprocessing.text import one_hot

In [40]:
### sentences
sent = ['The cat sat on the mat.', 'The dog sat on the log.', 'Cats and dogs are great pets.', 'The cat sat on the mat.', 'The dog sat on the log.', 'Cats and dogs are great pets.']

In [41]:
## Define the vocabulary size
voc_size=10000

In [42]:
## One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5828, 2342, 7753, 9186, 5828, 8224],
 [5828, 6846, 7753, 9186, 5828, 8019],
 [4445, 4010, 2975, 2542, 2807, 9770],
 [5828, 2342, 7753, 9186, 5828, 8224],
 [5828, 6846, 7753, 9186, 5828, 8019],
 [4445, 4010, 2975, 2542, 2807, 9770]]

In [43]:
## Word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [44]:
import numpy as np

In [45]:
sent_length=6
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[5828 2342 7753 9186 5828 8224]
 [5828 6846 7753 9186 5828 8019]
 [4445 4010 2975 2542 2807 9770]
 [5828 2342 7753 9186 5828 8224]
 [5828 6846 7753 9186 5828 8019]
 [4445 4010 2975 2542 2807 9770]]


In [46]:
## Feature representation
dim=10

In [47]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [48]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 309ms/step


array([[[-0.00275431,  0.01791758, -0.04676404,  0.04874356,
          0.03893259, -0.04717993,  0.04881725, -0.00031602,
          0.01573474,  0.02048265],
        [-0.0399912 ,  0.00966198,  0.02216568, -0.0402462 ,
         -0.03131651, -0.00588286, -0.03990548, -0.04036377,
          0.03766799,  0.02041775],
        [ 0.04769138,  0.03616813, -0.00847113, -0.02150064,
          0.04189478, -0.02003518, -0.03073131,  0.00300344,
          0.02475325,  0.04158235],
        [ 0.02302272, -0.00861398, -0.0478029 , -0.02513745,
          0.00405074, -0.00171777, -0.04108715, -0.01936289,
         -0.0356559 , -0.02636999],
        [-0.00275431,  0.01791758, -0.04676404,  0.04874356,
          0.03893259, -0.04717993,  0.04881725, -0.00031602,
          0.01573474,  0.02048265],
        [-0.01132118, -0.01419159, -0.01569701, -0.01874715,
         -0.02955413, -0.02238643,  0.0034504 , -0.01016264,
          0.00986495,  0.0407254 ]],

       [[-0.00275431,  0.01791758, -0.04676404,  0

In [51]:
embedded_docs[0]

array([5828, 2342, 7753, 9186, 5828, 8224], dtype=int32)

In [54]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[[-0.00275431,  0.01791758, -0.04676404,  0.04874356,
          0.03893259, -0.04717993,  0.04881725, -0.00031602,
          0.01573474,  0.02048265],
        [-0.0399912 ,  0.00966198,  0.02216568, -0.0402462 ,
         -0.03131651, -0.00588286, -0.03990548, -0.04036377,
          0.03766799,  0.02041775],
        [ 0.04769138,  0.03616813, -0.00847113, -0.02150064,
          0.04189478, -0.02003518, -0.03073131,  0.00300344,
          0.02475325,  0.04158235],
        [ 0.02302272, -0.00861398, -0.0478029 , -0.02513745,
          0.00405074, -0.00171777, -0.04108715, -0.01936289,
         -0.0356559 , -0.02636999],
        [-0.00275431,  0.01791758, -0.04676404,  0.04874356,
          0.03893259, -0.04717993,  0.04881725, -0.00031602,
          0.01573474,  0.02048265],
        [-0.01132118, -0.01419159, -0.01569701, -0.01874715,
         -0.02955413, -0.02238643,  0.0034504 , -0.01016264,
          0.00986495,  0.0407254 ]],

       [[-0.00275431,  0.01791758, -0.04676404,  0